<?php

namespace UsersBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	use \FBaseBundle\Repository\BaseRepository;

	function findUser($filter) {
		$qb = $this->createQueryBuilder('u');
        $qb->select('u');
        if (!empty($filter['name'])) {
            $qb
                ->andWhere($qb->expr()->orX(
                    $qb->expr()->like('u.username', ':name'),
                    $qb->expr()->like('u.firstName', ':name'),
                    $qb->expr()->like('u.middleName', ':name'),
                    $qb->expr()->like('u.lastName', ':name')
                ))
                ->setParameter('name', '%'.$filter['name'].'%');
        }

        if (!empty($filter['role'])) {
            $qb->andWhere($qb->expr()->like('u.roles', ':roles'))
                ->setParameter('roles', '%'.$filter['role'].'%');
        }

        return $qb->getQuery()->getResult();
	}
}
