<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContactRepository extends EntityRepository {

    use \FBaseBundle\Repository\BaseRepository;

}
