imports:
    - { resource: parameters.yml }
    - { resource: parameters.custom.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@FBaseBundle/Resources/config/services.yml" }
    - { resource: "@FBaseBundle/Resources/config/menu.yml" }
    - { resource: "@UsersBundle/Resources/config/services.yml" }
    - { resource: "@ParkingBundle/Resources/config/services.yml" }
  

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/DoctrineMigrations"
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations
#    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'fields.html.twig'
        - 'form/keen_validation.html.twig'
        - 'form/price_form.html.twig'
    globals:
        baseurl: '%baseurl%'
        i18n: '%i18n%'
        date_format_validation: '%date_format_validation%'

        menu: "@fbase.menu"
        permissions: "@user.permissions"
        notification: '@notification'
        ver: '%version%'
        helper: '@helper'
        

# Doctrine Configuration
doctrine:
    dbal:
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        #server_version: 'mariadb-10.3.17'
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    # auth_mode: '%mailer_auth_mode%'
    # spool: { type: memory }
    # spool: { type: file, path: '%kernel.project_dir%/var/spool'}

sensio_framework_extra:
   router:
        annotations: false

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
#        cssrewrite: ~
        cssrewrite:
            apply_to: "\\.css$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yui-compressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yui-compressor.jar"
        uglifyjs2:
           # bin: /usr/bin/terser
            #bin: /usr/local/bin/terser
#            bin: /usr/bin/uglifyjs
            bin: "%kernel.root_dir%/../node_modules/terser/bin/terser"
        uglifycss:
            bin: /usr/bin/uglifycss
    assets:
        base_nom_load_child:
            inputs:
                - '@FBaseBundle/Resources/public/js/basenomloadchild.js'
        base_nom_hint:
            inputs:
                - '@FBaseBundle/Resources/public/js/basenomHint.js'
        filters:
            inputs:
                - '@FBaseBundle/Resources/public/js/filters.js'
        summernote:
            inputs:
                - '@FBaseBundle/Resources/public/js/summernote.js'
        mask:
            inputs:
                - '@FBaseBundle/Resources/public/js/input-mask.js'
        child_entity:
            inputs:
                - '@FBaseBundle/Resources/public/js/entity_type_child.js'
        courses_tree_type:
            inputs:
                - '@FBaseBundle/Resources/public/js/courses_tree_type.js'


fkr_css_url_rewrite:
    rewrite_only_if_file_exists: true
    clear_urls: true

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UsersBundle\Entity\User
    from_email:
        address:        '%mail_sender%'
        sender_name:    'Our Team'
    registration:
        confirmation:
            enabled: true
            template: '@FOSUser/Registration/email.txt.twig'
        form:
            type: UsersBundle\Form\RegistrationType

translation:
    locales: ["en"]
    #auto_add_missing_translations:
    #    config_name: 'default'
    webui:
        enabled: true
    edit_in_place:
        enabled: true
        config_name: app # the first one or one of your configs
        activator: php_translation.edit_in_place.activator
    configs:
        app:
            dirs: ["%kernel.root_dir%/Resources/views", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
