<?php

namespace ParkingBundle\Repository;

/**
 * ParkingSpacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkingSpacesRepository extends \Doctrine\ORM\EntityRepository
{
}
