services:
#    f_base.example:
#        class: FBaseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  captcha_type:
        class: FBaseBundle\Form\Type\CaptchaType
        arguments: ["@service_container"]
        tags: [form.type]
        public: true
  helper:
        class: FBaseBundle\Service\Helper
        public: true
        arguments: ["@service_container"]
  